### ISSUE TITLE
Create Appointment data structure

### ISSUE THREAD

**Issue by JonD07** [psu-hbg-cmpsc-478-mr/clinic-system#7]
Create an Appointment data structure and give it basic appointment related fields.

**Comment by omegachysis** [comment]
I'll take this task. It will serve as a good template on where this stuff should go in the solution for others to refer to.

**Comment by omegachysis** [comment]
Delaying this, we should have any kind of data access in the dirty prototype. This will be instead part of the database context when the time comes.
